### ISSUE TITLE
[Quest][Loch Modan] Thistle While You Work

### ISSUE THREAD

**Issue by jacobx97** [NV-WoW/Bugtracker#156]
### What client do you play on?

Full (From Other Server)

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

1-20

### Current Behaviour

Stabthistle Seeds are missing

### Expected Blizzlike Behaviour

There should be seeds spawned under trees.

https://www.youtube.com/watch?v=Gjrrttn0Xxo

### Source

https://www.wowhead.com/quest=27025/thistle-while-you-work
https://www.wowhead.com/item=60737/stabthistle-seed

### Steps to reproduce the problem

1. Take the quest
2. Go to location where seeds should be

**Comment by xadowtek** [comment]
Fixed and tested on my private server.
SQL:
-- Fix Quest 27025 no loot
UPDATE gameobject_template SET type = '3' WHERE entry = '205089';
DELETE FROM gameobject_loot_template WHERE item = '60737';
INSERT INTO gameobject_loot_template (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES (205089, 60737, -100, 1, 0, 1, 1);

**Comment by Mezma99** [comment]
Quest is still not working. Seeds are showing up, but you cant pick them up. 
![WoWScrnShot_081921_141146](https://user-images.githubusercontent.com/89113397/130122434-06910909-227c-4296-9157-aec49a76f8f1.jpg)
