### ISSUE TITLE
Lou's Parting Thoughts quest bugged in Westfall

### ISSUE THREAD

**Issue by l0ssm1** [NV-WoW/Bugtracker#20]
Quest isn't working at all. Thugs that you need to eavesdrop/go near are going to start attacking when you get close to them, and when you kill them quest doesn't complete. Also they can aggro through walls and attack while dead. Me and another player tested this quest multiple times and found that every single time it is in fact not working as intended.

Wowhead link to the quest: https://www.wowhead.com/quest=26232/lous-parting-thoughts
Youtube video of how the quest should work: https://www.youtube.com/watch?time_continue=116&v=SZcjX3cDRUQ&feature=emb_title

**Comment by sar4nix** [comment]
i confirm this

**Comment by l0ssm1** [comment]
I tried it again while every single mob was alive and they were all aggressive and it still didn't work.

**Comment by wr4i7h-gg** [comment]
The proper encounter trigger and quest credit have been fixed.
If the issue will persist again, refer to this report.

**Comment by Jinmcx** [comment]
Still doesn't work, needs to be reopen - 8/17/21
![WoWScrnShot_081821_030456](https://user-images.githubusercontent.com/19652090/129971371-e0ca0d21-4e4b-456c-9274-918397d92f69.jpg)
